### ISSUE TITLE
KaSaAn gets lost when snapshot contains tokens.

### ISSUE THREAD

**Issue by jkrivine** [hmedina/KaSaAn#1]
I think tokens should be ignored (they are not complexes).

**Comment by hmedina** [comment]
I agree with you, and f8766507d8d824dde4038b0bd46143df382fb1a0 should have fixed that; however the syntax for tokens has changed in KaSim, but not in the UI. Previously I relied on tokens being of the form `%init: X <- 241.000000` whereas now they differ from agent statements only in not having the agent number comment preceding the kappa expression.

UI says:
```
%init: 18 /*1 agents*/ A(a)
%init: X <- 241.000000
```

KaSim says:
```
%init: 18 /*1 agents*/ A(a)
%init: 241 X
```

I'll contact the powers that be and see what syntax will be adopted moving on.

**Comment by hmedina** [comment]
Could you check it's working in your setup / with your token names?

**Comment by hmedina** [comment]
I'll assume it is working now.
